You can use this template for problems 1, 2 and 3

*   List item
*   List item



In [ ]:
import numpy as np
import time
import math
# Students will submit their files with their team-name.py
# Student have to use the Team as their parent class

Recent Version of the Code

In [ ]:
def KL(x, y,eps = 1e-15):
    x = min(max(x, eps), 1 - eps)
    y = min(max(y, eps), 1 - eps)
    return x * np.log(x / y) + (1 - x) * np.log((1 - x) / (1 - y))

def KLmaxUCB(c,t):
	return math.log(t) + c*math.log(math.log(t))

def KLupperConfidenceBound(p, u, c, t):
	maxBound = KLmaxUCB(c,t)/u
	q = p
	b = (1 - p) / 2
	while b > 1e-4:
		if KL(p,q+b) <= maxBound:
			q += b
		b /= 2;
	return q


In [ ]:
class Agent:
  def __init__(self):
      pass

  def get_action(self,wicket,runs_scored):
    action = np.random.randint(0,6)
    return action

  def get_action_p1(self,wicket,runs_scored):
    pass

  def get_action_p2(self,wicket,runs_scored):
    pass

In [ ]:
class Environment:
  def __init__(self,num_balls,agent):
    self.num_balls = num_balls
    self.agent = agent
    self.__run_time = 0
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0
    self.__start_time = 0
    self.__end_time = 0
    self.__regret_w = 0
    self.__regret_s = 0
    self.__wicket = 0
    self.__regret_rho = 0
    self.__p_out =np.array([0.001,0.01,0.02,0.03,0.1,0.3])
    self.__p_run =np.array([1,0.9,0.85,0.8,0.75,0.7])
    self.__action_runs_map = np.array([0,1,2,3,4,6])
    self.__s = (1-self.__p_out)*self.__p_run*self.__action_runs_map
    self.__rho = self.__s/self.__p_out


  def __get_action(self):
    self.__start_time      = time. time()
    action          = self.agent.get_action(self.__wicket,self.__runs_scored)
    self.__end_time        = time. time()
    self.__run_time   = self.__run_time + self.__end_time - self.__start_time
    return action


  def __get_outcome(self, action):
    pout = self.__p_out[action]
    prun= self.__p_run[action]
    wicket = np.random.choice(2,1,p=[1-pout,pout])[0]
    runs = 0
    if(wicket==0):
      run_probab=np.random.choice(2, 1, p=[1 - prun, prun])[0]
      runs = self.__action_runs_map[action]*(run_probab) + (1-run_probab)*(np.random.choice(self.__action_runs_map,1,p=(self.__p_run/sum(self.__p_run))))[0]
    return wicket, runs


  def innings(self):
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0

    no_arms=len(self.__action_runs_map)
    arm_pulls=np.zeros(no_arms)
    sample_means=np.zeros(no_arms)
    runs=[]
    klucb_estimates=np.zeros(no_arms)
    for action in range(no_arms):





      self.__wicket, self.__runs_scored   = self.__get_outcome(action)

      sample_means[action]+=(self.__wicket)
      arm_pulls[action]+=1




      self.__total_runs     = self.__total_runs + self.__runs_scored
      self.__total_wickets  = self.__total_wickets + self.__wicket
      self.__regret_w       = self.__regret_w+ (self.__p_out[action]-np.min(self.__p_out))
      self.__regret_s       = self.__regret_s+ (np.max(self.__s) - self.__s[action])
      self.__regret_rho       = self.__regret_rho+ (np.max(self.__rho)-self.__rho[action])






    for ball in range(no_arms,self.num_balls):
      # action = self.__get_action()
      #print([KLupperConfidenceBound(p=(sample_means[i]/arm_pulls[i]),u=arm_pulls[i],c=3,t=ball+1) for i in range(no_arms)])
      action=np.argmin([KLupperConfidenceBound(p=(sample_means[i]/arm_pulls[i]),u=arm_pulls[i],c=3,t=ball+1) for i in range(no_arms)])



      self.__wicket, self.__runs_scored   = self.__get_outcome(action)
      sample_means[action]+=(self.__wicket)
      #print(action,"wicket:",self.__wicket)
      arm_pulls[action]+=1

      self.__total_runs     = self.__total_runs + self.__runs_scored
      self.__total_wickets  = self.__total_wickets + self.__wicket
      self.__regret_w       = self.__regret_w+ (self.__p_out[action]-np.min(self.__p_out))
      self.__regret_s       = self.__regret_s+ (np.max(self.__s) - self.__s[action])
      self.__regret_rho       = self.__regret_rho+ (np.max(self.__rho)-self.__rho[action])
    return self.__regret_w,self.__regret_s,self.__regret_rho, self.__total_runs, self.__total_wickets, self.__run_time


In [ ]:
agent = Agent()
environment = Environment(1000,agent)
regret_w,regret_s,reger_rho,total_runs,total_wickets,run_time = environment.innings()

In [ ]:
print(regret_w,regret_s,reger_rho,total_runs,total_wickets,run_time)

0.45499999999999996 2929.4750000000445 88813.20000000077 16 1 0


In [ ]:
### Experiments
np.random.choice(5,1
                 )

array([4])

Problem 2

In [ ]:
class Environment:
  def __init__(self,num_balls,agent):
    self.num_balls = num_balls
    self.agent = agent
    self.__run_time = 0
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0
    self.__start_time = 0
    self.__end_time = 0
    self.__regret_w = 0
    self.__regret_s = 0
    self.__wicket = 0
    self.__regret_rho = 0
    self.__p_out =np.array([0.001,0.01,0.02,0.03,0.1,0.3])
    self.__p_run =np.array([1,0.9,0.85,0.8,0.75,0.7])
    self.__action_runs_map = np.array([0,1,2,3,4,6])
    self.__s = (1-self.__p_out)*self.__p_run*self.__action_runs_map
    self.__rho = self.__s/self.__p_out


  def __get_action(self):
    self.__start_time      = time. time()
    action          = self.agent.get_action(self.__wicket,self.__runs_scored)
    self.__end_time        = time. time()
    self.__run_time   = self.__run_time + self.__end_time - self.__start_time
    return action


  def __get_outcome(self, action):
    pout = self.__p_out[action]
    prun= self.__p_run[action]
    wicket = np.random.choice(2,1,p=[1-pout,pout])[0]
    runs = 0
    if(wicket==0):
      run_probab=np.random.choice(2, 1, p=[1 - prun, prun])[0]
      runs = self.__action_runs_map[action]*(run_probab) + (1-run_probab)*(np.random.choice(self.__action_runs_map,1,p=(self.__p_run/sum(self.__p_run))))[0]
    return wicket, runs


  def innings(self):
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0

    no_arms=len(self.__action_runs_map)
    arm_pulls=np.zeros(no_arms)
    sample_means=np.zeros(no_arms)
    runs=[]
    klucb_estimates=np.zeros(no_arms)
    for action in range(no_arms):





      self.__wicket, self.__runs_scored   = self.__get_outcome(action)

      sample_means[action]+=(self.__runs_scored/max(self.__action_runs_map))
      arm_pulls[action]+=1




      self.__total_runs     = self.__total_runs + self.__runs_scored
      self.__total_wickets  = self.__total_wickets + self.__wicket
      self.__regret_w       = self.__regret_w+ (self.__p_out[action]-np.min(self.__p_out))
      self.__regret_s       = self.__regret_s+ (np.max(self.__s) - self.__s[action])
      self.__regret_rho       = self.__regret_rho+ (np.max(self.__rho)-self.__rho[action])






    for ball in range(no_arms,self.num_balls):
      # action = self.__get_action()
      # print([KLupperConfidenceBound(p=(sample_means[i]/arm_pulls[i]),u=arm_pulls[i],c=3,t=ball+1) for i in range(no_arms)])
      # print(sample_means)
      action=np.argmax([KLupperConfidenceBound(p=(sample_means[i]/arm_pulls[i]),u=arm_pulls[i],c=3,t=ball+1) for i in range(no_arms)])
      #print(action)


      self.__wicket, self.__runs_scored   = self.__get_outcome(action)
      sample_means[action]+=(self.__runs_scored/max(self.__action_runs_map))
      #print(action,"wicket:",self.__wicket)
      arm_pulls[action]+=1

      self.__total_runs     = self.__total_runs + self.__runs_scored
      self.__total_wickets  = self.__total_wickets + self.__wicket
      self.__regret_w       = self.__regret_w+ (self.__p_out[action]-np.min(self.__p_out))
      self.__regret_s       = self.__regret_s+ (np.max(self.__s) - self.__s[action])
      self.__regret_rho       = self.__regret_rho+ (np.max(self.__rho)-self.__rho[action])
    return self.__regret_w,self.__regret_s,self.__regret_rho, self.__total_runs, self.__total_wickets, self.__run_time


In [ ]:
agent = Agent()
environment = Environment(1000,agent)
regret_w,regret_s,reger_rho,total_runs,total_wickets,run_time = environment.innings()

In [ ]:
print(regret_w,regret_s,reger_rho,total_runs,total_wickets,run_time)

191.08100000000184 285.15800000000155 60992.700000000485 3171 185 0


Problem3

In [ ]:
class Environment:
  def __init__(self,num_balls,agent):
    self.num_balls = num_balls
    self.agent = agent
    self.__run_time = 0
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0
    self.__start_time = 0
    self.__end_time = 0
    self.__regret_w = 0
    self.__regret_s = 0
    self.__wicket = 0
    self.__regret_rho = 0
    self.__p_out =np.array([0.001,0.01,0.02,0.03,0.1,0.3])
    self.__p_run =np.array([1,0.9,0.85,0.8,0.75,0.7])
    self.__action_runs_map = np.array([0,1,2,3,4,6])
    self.__s = (1-self.__p_out)*self.__p_run*self.__action_runs_map
    self.__rho = self.__s/self.__p_out


  def __get_action(self):
    self.__start_time      = time. time()
    action          = self.agent.get_action(self.__wicket,self.__runs_scored)
    self.__end_time        = time. time()
    self.__run_time   = self.__run_time + self.__end_time - self.__start_time
    return action


  def __get_outcome(self, action):
    pout = self.__p_out[action]
    prun= self.__p_run[action]
    wicket = np.random.choice(2,1,p=[1-pout,pout])[0]
    runs = 0
    if(wicket==0):
      runs = self.__action_runs_map[action]*np.random.choice(2,1,p=[1-prun,prun])[0]
    return wicket, runs


  def innings(self):
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0

    t=1
    delta=0.05
    actions=np.array([0,1,2,3,4])
    action_runs_map = np.array([0,1,2,3,4,6])
    K=len(actions)
    arm_runs=np.zeros(K)
    arm_pulls=np.zeros(K)
    arm_wickets=np.zeros(K)
    mean_rewards=np.zeros(K)
    mean_cost=np.zeros(K)
    var_rewards=np.zeros(K)
    var_cost=np.zeros(K)
    rate_estimator=np.zeros(K)
    S=np.array([0,1,2,3,4,5])
    while len(actions)>1:
      print("Iteration",t)
      print("action",actions)
      print(arm_runs,arm_wickets)
      if t>10:
        for ind in actions:
          if arm_runs[ind]==0:
            actions=actions[actions != ind]
      for ind in actions:
        wicket,run=self.__get_outcome(ind)
        arm_pulls[ind]+=1
        arm_runs[ind]+= run
        arm_wickets[ind]+=wicket
        rate_estimator[ind]= ((arm_runs[ind]+1)/(arm_wickets[ind]+1))
      best_rate= max(rate_estimator)
      best_arm= np.argmax(rate_estimator)

      beta_t= np.sqrt(np.log(4*K/delta)/(2*t))
      if arm_runs[best_arm]-2*beta_t<=0:
        t+=1
      else:
        to_remove=[]
        for arm in actions[actions != best_arm]:
          if arm_runs[arm]-2*beta_t<=0:
            continue
          elif (((arm_runs[best_arm]-2*beta_t)/(arm_wickets[best_arm]+2*beta_t))> ((arm_runs[arm]+2*beta_t)/(arm_wickets[arm]-2*beta_t))):
            to_remove.append(arm)

        for ele in to_remove:
          actions=actions[actions != ele]
        t+=1


    print(actions)
    print(rate_estimator)
    print(self.__rho)












    # for ball in range(no_arms,self.num_balls):
    #   # action = self.__get_action()
    #   # print([KLupperConfidenceBound(p=(sample_means[i]/arm_pulls[i]),u=arm_pulls[i],c=3,t=ball+1) for i in range(no_arms)])
    #   # print(sample_means)
    #   action=np.argmax([KLupperConfidenceBound(p=(sample_means[i]/arm_pulls[i]),u=arm_pulls[i],c=3,t=ball+1) for i in range(no_arms)])
    #   print(action)


    #   self.__wicket, self.__runs_scored   = self.__get_outcome(action)
    #   sample_means[action]+=(self.__runs_scored/max(self.__action_runs_map))
    #   print(action,"wicket:",self.__wicket)
    #   arm_pulls[action]+=1

    #   self.__total_runs     = self.__total_runs + self.__runs_scored
    #   self.__total_wickets  = self.__total_wickets + self.__wicket
    #   self.__regret_w       = self.__regret_w+ (self.__p_out[action]-np.min(self.__p_out))
    #   self.__regret_s       = self.__regret_s+ (np.max(self.__s) - self.__s[action])
    #   self.__regret_rho       = self.__regret_rho+ (np.max(self.__rho)-self.__rho[action])
    # return self.__regret_w,self.__regret_s,self.__regret_rho, self.__total_runs, self.__total_wickets, self.__run_time


In [ ]:
agent = Agent()
environment = Environment(1,agent)
environment.innings()

Iteration 1
action [0 1 2 3 4]
[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
Iteration 2
action [0 1 2 3 4]
[0. 1. 2. 3. 4.] [0. 0. 0. 0. 0.]
Iteration 3
action [0 1 2 3 4]
[0. 2. 2. 6. 4.] [0. 0. 1. 0. 0.]
Iteration 4
action [0 1 2 3 4]
[0. 3. 4. 9. 8.] [0. 0. 1. 0. 0.]
Iteration 5
action [0 1 2 3 4]
[ 0.  3.  6. 12.  8.] [0. 0. 1. 0. 0.]
Iteration 6
action [0 1 2 3 4]
[ 0.  4.  6. 15. 12.] [0. 0. 2. 0. 0.]
Iteration 7
action [0 1 2 3 4]
[ 0.  5.  8. 18. 12.] [0. 0. 2. 0. 0.]
Iteration 8
action [0 1 2 3 4]
[ 0.  6. 10. 21. 12.] [0. 0. 2. 0. 1.]
Iteration 9
action [0 1 3 4]
[ 0.  7. 10. 21. 16.] [0. 0. 2. 0. 1.]
Iteration 10
action [0 1 3 4]
[ 0.  8. 10. 24. 20.] [0. 0. 2. 0. 1.]
Iteration 11
action [0 1 3 4]
[ 0.  9. 10. 24. 24.] [0. 0. 2. 1. 1.]
Iteration 12
action [1 3 4]
[ 0. 10. 10. 27. 28.] [0. 0. 2. 1. 1.]
Iteration 13
action [1 3 4]
[ 0. 11. 10. 30. 32.] [0. 0. 2. 1. 1.]
Iteration 14
action [1 3 4]
[ 0. 12. 10. 33. 36.] [0. 0. 2. 1. 1.]
Iteration 15
action [1 3 4]
[ 0. 13. 10. 36. 36.] [0.

In [ ]:
print(regret_w,regret_s,reger_rho,total_runs,total_wickets,run_time)

179.88100000000173 299.00200000000206 59514.30000000029 3206 179 0


In [ ]:
actions=np.array([0,1,2,3,4,5])
actions=actions[actions != 5]

In [ ]:
actions


array([0, 1, 2, 3, 4])