You can use this template for problems 1, 2 and 3

In [1]:
import numpy as np
import time
# Students will submit their files with their team-name.py
# Student have to use the Team as their parent class

Recent Version of the Code

In [2]:
class Agent:
  def __init__(self):
      self.actions=np.array([0,1,2,3,4,5])
      self.balls=0
      self.K=len(self.actions)
      self.arm_rewards=np.zeros(self.K)
      self.arm_costs=np.zeros(self.K)
      self.prev_action=0
      self.act_ind=0
      self.iter=1
      self.delta=0.05
      self.rate_estimator=np.zeros(self.K)

  def get_action(self,wicket,runs_scored):
    print(self.actions)
    if self.balls==0:
      self.balls+=1
      return 0

    if len(self.actions)==1:
      self.balls+=1
      print(self.actions[0])
      return self.actions[0]

    if self.act_ind<len(self.actions):
      self.arm_rewards[self.prev_action]+= runs_scored
      self.arm_costs[self.prev_action]+= wicket

      action = self.actions[self.act_ind]
      self.act_ind+=1
      self.prev_action=action

    else:
      self.arm_rewards[self.prev_action]+= runs_scored
      self.arm_costs[self.prev_action]+= wicket

      best_arm=np.argmax([(self.arm_rewards[i]+1e-6)/(self.arm_costs[i]+1e-6) for i in self.actions])
      beta_t= np.sqrt(np.log(4*self.K/self.delta)/2*self.iter)

      for arm in self.actions[self.actions != best_arm]:
        if self.arm_rewards[arm]-2*beta_t<=0:
          continue
        elif ((self.arm_rewards[best_arm]-2*beta_t)/(self.arm_costs[best_arm]+2*beta_t))> ((self.arm_rewards[arm]+2*beta_t)/(self.arm_costs[arm]-2*beta_t)):
          self.actions=self.actions[self.actions!=arm]
      self.act_ind=0
      action=self.actions[self.act_ind]
      self.act_ind+=1
      self.prev_action=action
      self.iter+=1
    print(action)
    return action




In [3]:
class Environment:
  def __init__(self,num_balls,agent):
    self.num_balls = num_balls
    self.agent = agent
    self.__run_time = 0
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0
    self.__start_time = 0
    self.__end_time = 0
    self.__regret_w = 0
    self.__regret_s = 0
    self.__wicket = 0
    self.__regret_rho = 0
    self.__p_out =np.array([0.001,0.01,0.02,0.03,0.1,0.3])
    self.__p_run =np.array([1,0.9,0.85,0.8,0.75,0.7])
    self.__action_runs_map = np.array([0,1,2,3,4,6])
    self.__s = (1-self.__p_out)*self.__p_run*self.__action_runs_map
    self.__rho = self.__s/self.__p_out


  def __get_action(self):
    self.__start_time      = time. time()
    action          = self.agent.get_action(self.__wicket,self.__runs_scored)
    self.__end_time        = time. time()
    self.__run_time   = self.__run_time + self.__end_time - self.__start_time
    return action


  def __get_outcome(self, action):
    pout = self.__p_out[action]
    prun= self.__p_run[action]
    wicket = np.random.choice(2,1,p=[1-pout,pout])[0]
    runs = 0
    if(wicket==0):
      runs = self.__action_runs_map[action]*np.random.choice(2,1,p=[1-prun,prun])[0]
    return wicket, runs


  def innings(self):
    self.__total_runs = 0
    self.__total_wickets = 0
    self.__runs_scored = 0

    for ball in range(self.num_balls):
      action = self.__get_action()
      self.__wicket, self.__runs_scored   = self.__get_outcome(action)
      self.__total_runs     = self.__total_runs + self.__runs_scored
      self.__total_wickets  = self.__total_wickets + self.__wicket
      self.__regret_w       = self.__regret_w+ (self.__p_out[action]-np.min(self.__p_out))
      self.__regret_s       = self.__regret_s+ (np.max(self.__s) - self.__s[action])
      self.__regret_rho       = self.__regret_rho+ (np.max(self.__rho)-self.__rho[action])
    return self.__regret_w,self.__regret_s,self.__regret_rho, self.__total_runs, self.__total_wickets, self.__run_time


In [4]:
agent = Agent()
environment = Environment(100,agent)
regret_w,regret_s,reger_rho,total_runs,total_wickets,run_time = environment.innings()

[0 1 2 3 4 5]
[0 1 2 3 4 5]
0
[0 1 2 3 4 5]
1
[0 1 2 3 4 5]
2
[0 1 2 3 4 5]
3
[0 1 2 3 4 5]
4
[0 1 2 3 4 5]
5
[0 1 2 3 4 5]
0
[0 1 2 3 4 5]
1
[0 1 2 3 4 5]
2
[0 1 2 3 4 5]
3
[0 1 2 3 4 5]
4
[0 1 2 3 4 5]
5
[0 1 2 3 4 5]
0
[0 1 2 3 4]
1
[0 1 2 3 4]
2
[0 1 2 3 4]
3
[0 1 2 3 4]
4
[0 1 2 3 4]
0
[0 1 2 3 4]
1
[0 1 2 3 4]
2
[0 1 2 3 4]
3
[0 1 2 3 4]
4
[0 1 2 3 4]
0
[0 1 2 3 4]
1
[0 1 2 3 4]
2
[0 1 2 3 4]
3
[0 1 2 3 4]
4
[0 1 2 3 4]
0
[0 1 2 3]
1
[0 1 2 3]
2
[0 1 2 3]
3
[0 1 2 3]
0
[0 1 2 3]
1
[0 1 2 3]
2
[0 1 2 3]
3
[0 1 2 3]
0
[0 1 3]
1
[0 1 3]
3
[0 1 3]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0 1]
0
[0 1]
1
[0

In [ ]:
print(regret_w,regret_s,reger_rho,total_runs,total_wickets,run_time)

1.3439999999999963 225.7000000000001 4239.099999999998 69 0 0.04131031036376953
